.TH "Display" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Display
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Display\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBDisplay\fP (\fBConsole\fP *console)"
.br
.ti -1c
.RI "virtual \fB~Display\fP ()"
.br
.ti -1c
.RI "int \fBInputCommand\fP (char *input, const int len)"
.br
.RI "命令行输入控制 "
.ti -1c
.RI "void \fBrender\fP ()"
.br
.RI "命令行提示符显示模块 "
.ti -1c
.RI "void \fBprompt\fP () const"
.br
.RI "继续输入提示 "
.ti -1c
.RI "void \fBmessage\fP (const char *msg)"
.br
.RI "打印信息msg与显示器 "
.ti -1c
.RI "void \fBshow\fP () const"
.br
.RI "将所有打印信息统一显示在终端 "
.ti -1c
.RI "void \fBclear\fP ()"
.br
.RI "清空缓冲区 "
.in -1c
.SS "Protected 属性"

.in +1c
.ti -1c
.RI "std::string \fBbuffer_\fP"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "\fBConsole\fP * \fBconsole_\fP"
.br
.ti -1c
.RI "bool \fBperform\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBDisplay\&.h\fP 第 \fB19\fP 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "Display::Display (\fBConsole\fP * console)"

.PP
在文件 \fBDisplay\&.cpp\fP 第 \fB20\fP 行定义\&.
.SS "Display::~Display ()\fC [virtual]\fP"

.PP
在文件 \fBDisplay\&.cpp\fP 第 \fB25\fP 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void Display::clear ()\fC [inline]\fP"

.PP
清空缓冲区 
.PP
在文件 \fBDisplay\&.h\fP 第 \fB55\fP 行定义\&.
.SS "int Display::InputCommand (char * input, const int len)"

.PP
命令行输入控制 
.PP
\fB返回\fP
.RS 4
正数表示正常退出，返回读入的字符数； 返回0表示读到EOF，返回负数表示出现错误 
.RE
.PP

.PP
在文件 \fBDisplay\&.cpp\fP 第 \fB29\fP 行定义\&.
.SS "void Display::message (const char * msg)"

.PP
打印信息msg与显示器 
.PP
在文件 \fBDisplay\&.cpp\fP 第 \fB147\fP 行定义\&.
.SS "void Display::prompt () const"

.PP
继续输入提示 
.PP
在文件 \fBDisplay\&.cpp\fP 第 \fB139\fP 行定义\&.
.SS "void Display::render ()"

.PP
命令行提示符显示模块 
.PP
在文件 \fBDisplay\&.cpp\fP 第 \fB88\fP 行定义\&.
.SS "void Display::show () const"

.PP
将所有打印信息统一显示在终端 
.PP
在文件 \fBDisplay\&.cpp\fP 第 \fB152\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "std::string Display::buffer_\fC [protected]\fP"

.PP
在文件 \fBDisplay\&.h\fP 第 \fB28\fP 行定义\&.
.SS "\fBConsole\fP* Display::console_\fC [private]\fP"

.PP
在文件 \fBDisplay\&.h\fP 第 \fB23\fP 行定义\&.
.SS "bool Display::perform\fC [private]\fP"

.PP
在文件 \fBDisplay\&.h\fP 第 \fB25\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 My Shell 的 源代码自动生成\&.
