.TH "src 目录参考" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBcommon\&.cpp\fP"
.br
.RI "共享函数库 "
.ti -1c
.RI "文件 \fBConsole\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBDisplay\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBExecutor\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBlexer\&.l\fP"
.br
.ti -1c
.RI "文件 \fBmyshell\&.cpp\fP"
.br
.RI "myshell程序的main函数，负责调用各个接口并实现myshell功能 "
.ti -1c
.RI "文件 \fBParser\&.cpp\fP"
.br
.RI "语法分析 "
.ti -1c
.RI "文件 \fBProcessManager\&.cpp\fP"
.br
.in -1c
