.TH "inc 目录参考" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBBinaryHeap\&.h\fP"
.br
.RI "二叉堆 "
.ti -1c
.RI "文件 \fBcommon\&.h\fP"
.br
.RI "共享函数库 "
.ti -1c
.RI "文件 \fBconfig\&.h\fP"
.br
.ti -1c
.RI "文件 \fBConsole\&.h\fP"
.br
.ti -1c
.RI "文件 \fBDisplay\&.h\fP"
.br
.ti -1c
.RI "文件 \fBExecutor\&.h\fP"
.br
.ti -1c
.RI "文件 \fBHeap\&.h\fP"
.br
.RI "堆，抽象类 "
.ti -1c
.RI "文件 \fBmyshell\&.h\fP"
.br
.RI "myshell头文件 包含了myshell\&.cpp中所需要引用的所有自定义类 "
.ti -1c
.RI "文件 \fBParser\&.h\fP"
.br
.RI "语法分析 "
.ti -1c
.RI "文件 \fBProcessManager\&.h\fP"
.br
.RI "进程管理 "
.in -1c
