.TH "inc/Executor.h" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/Executor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBExecutor\fP"
.br
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "static constexpr int \fBFunctionNumber\fP = 16"
.br
.in -1c
.SH "详细描述"
.PP 

.PP
\fB作者\fP
.RS 4
邱日宏 (3200105842@zju.edu.cn) 
.RE
.PP
\fB版本\fP
.RS 4
0\&.1 
.RE
.PP
\fB日期\fP
.RS 4
2022-07-04
.RE
.PP
\fB版权所有\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
在文件 \fBExecutor\&.h\fP 中定义\&.
.SH "变量说明"
.PP 
.SS "constexpr int FunctionNumber = 16\fC [static]\fP, \fC [constexpr]\fP"

.PP
在文件 \fBExecutor\&.h\fP 第 \fB20\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 My Shell 的 源代码自动生成\&.
