.TH "src/Executor.cpp" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Executor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'myshell\&.h'\fP
.br
\fC#include 'Console\&.h'\fP
.br
\fC#include 'Display\&.h'\fP
.br
\fC#include 'Executor\&.h'\fP
.br
\fC#include 'ProcessManager\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "static bool \fBtest_tty\fP (const char *file_name)"
.br
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "static const char * \fBOperandArray\fP []"
.br
.in -1c
.SH "详细描述"
.PP 

.PP
\fB作者\fP
.RS 4
邱日宏 (3200105842@zju.edu.cn) 
.RE
.PP
\fB版本\fP
.RS 4
0\&.1 
.RE
.PP
\fB日期\fP
.RS 4
2022-07-04
.RE
.PP
\fB版权所有\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
在文件 \fBExecutor\&.cpp\fP 中定义\&.
.SH "函数说明"
.PP 
.SS "static bool test_tty (const char * file_name)\fC [inline]\fP, \fC [static]\fP"
测试终端联系 
.PP
在文件 \fBExecutor\&.cpp\fP 第 \fB841\fP 行定义\&.
.SH "变量说明"
.PP 
.SS "const char* OperandArray[]\fC [static]\fP"
\fB初始值:\fP
.PP
.nf
= 
{
    "bg", "cd", "clr", "dir", "echo", "exec", "exit", "fg",
    "help", "jobs", "myshell", "pwd", "set", "test", "time", "umask"
}
.fi
定义命令字符串数组 
.PP
在文件 \fBExecutor\&.cpp\fP 第 \fB36\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 My Shell 的 源代码自动生成\&.
