.TH "main.cpp" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 主函数  

.SH SYNOPSIS
.br
.PP
\fC#include 'myshell\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[], char **env)"
.br
.in -1c
.SH "详细描述"
.PP 
主函数 


.PP
\fB作者\fP
.RS 4
邱日宏 (3200105842@zju.edu.cn) 
.RE
.PP
\fB版本\fP
.RS 4
0\&.1 
.RE
.PP
\fB日期\fP
.RS 4
2022-07-17
.RE
.PP
\fB版权所有\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
在文件 \fBmain\&.cpp\fP 中定义\&.
.SH "函数说明"
.PP 
.SS "int main (int argc, char * argv[], char ** env)"

.PP
在文件 \fBmain\&.cpp\fP 第 \fB19\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 My Shell 的 源代码自动生成\&.
