.TH "Parser" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parser\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBParser\fP ()"
.br
.ti -1c
.RI "virtual \fB~Parser\fP ()=0"
.br
.RI "Destroy the \fBParser\fP object "
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static bool \fBshell_pipe\fP (\fBConsole\fP *model, \fBDisplay\fP *view, \fBExecutor\fP *controller, int &argc, char *argv[], char *env[])"
.br
.ti -1c
.RI "static int \fBshell_parser\fP (\fBConsole\fP *model, \fBDisplay\fP *view, \fBExecutor\fP *controller, int &argc, char *argv[], char *env[])"
.br
.in -1c
.SS "Private 类型"

.in +1c
.ti -1c
.RI "enum { \fBSUCCESS\fP = 0, \fBEXIT\fP = 1 }"
.br
.in -1c
.SS "静态 Private 成员函数"

.in +1c
.ti -1c
.RI "static bool \fBshell_execute\fP (\fBConsole\fP *model, \fBDisplay\fP *view, \fBExecutor\fP *controller, int &argc, char *argv[], char *env[])"
.br
.RI "执行shell "
.in -1c
.SH "详细描述"
.PP 
在文件 \fBParser\&.h\fP 第 \fB19\fP 行定义\&.
.SH "成员枚举类型说明"
.PP 
.SS "anonymous enum\fC [private]\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fISUCCESS \fP\fP
.TP
\fB\fIEXIT \fP\fP
.PP
在文件 \fBParser\&.h\fP 第 \fB22\fP 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "Parser::Parser ()\fC [inline]\fP"

.PP
在文件 \fBParser\&.h\fP 第 \fB43\fP 行定义\&.
.SS "virtual Parser::~Parser ()\fC [pure virtual]\fP"

.PP
Destroy the \fBParser\fP object 
.PP
\fB版本\fP
.RS 4
0\&.1 
.RE
.PP
\fB作者\fP
.RS 4
邱日宏 (3200105842@zju.edu.cn) 
.RE
.PP
\fB日期\fP
.RS 4
2022-07-19 
.RE
.PP
\fB版权所有\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "成员函数说明"
.PP 
.SS "bool Parser::shell_execute (\fBConsole\fP * model, \fBDisplay\fP * view, \fBExecutor\fP * controller, int & argc, char * argv[], char * env[])\fC [static]\fP, \fC [private]\fP"

.PP
执行shell 
.PP
\fB参数\fP
.RS 4
\fImodel\fP 
.br
\fIview\fP 
.br
\fIcontroller\fP 
.br
\fIargc\fP 
.br
\fIargv\fP 
.br
\fIenv\fP 
.RE
.PP
\fB返回\fP
.RS 4
true 
.PP
false 
.RE
.PP
\fB版本\fP
.RS 4
0\&.1 
.RE
.PP
\fB作者\fP
.RS 4
邱日宏 (3200105842@zju.edu.cn) 
.RE
.PP
\fB日期\fP
.RS 4
2022-07-19 
.RE
.PP
\fB版权所有\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
在文件 \fBParser\&.cpp\fP 第 \fB268\fP 行定义\&.
.SS "int Parser::shell_parser (\fBConsole\fP * model, \fBDisplay\fP * view, \fBExecutor\fP * controller, int & argc, char * argv[], char * env[])\fC [static]\fP"
重定向处理
.PP
标准输入重定向
.PP
标准输出重定向
.PP
标准错误输出重定向
.PP
追加
.PP
在文件 \fBParser\&.cpp\fP 第 \fB132\fP 行定义\&.
.SS "bool Parser::shell_pipe (\fBConsole\fP * model, \fBDisplay\fP * view, \fBExecutor\fP * controller, int & argc, char * argv[], char * env[])\fC [static]\fP"

.PP
在文件 \fBParser\&.cpp\fP 第 \fB27\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 My Shell 的 源代码自动生成\&.
