.TH "inc/ProcessManager.h" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/ProcessManager.h \- 进程管理  

.SH SYNOPSIS
.br
.PP
\fC#include 'Heap\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br
\fC#include <set>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBjob_unit\fP"
.br
.ti -1c
.RI "class \fBProcessManager\fP"
.br
.in -1c
.SH "详细描述"
.PP 
进程管理 


.PP
\fB作者\fP
.RS 4
邱日宏 (3200105842@zju.edu.cn) 
.RE
.PP
\fB版本\fP
.RS 4
0\&.1 
.RE
.PP
\fB日期\fP
.RS 4
2022-08-10
.RE
.PP
\fB版权所有\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.PP
在文件 \fBProcessManager\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 My Shell 的 源代码自动生成\&.
