.TH "SHELL" 3 "2022年 八月 13日 星期六" "Version 1.0.0" "My Shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SHELL
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "int \fBshell_setup\fP (int argc, char *argv[], char *env[])"
.br
.RI "启动shell "
.ti -1c
.RI "int \fBshell_loop\fP (\fBConsole\fP *model, \fBDisplay\fP *view, \fBExecutor\fP *controller, char *env[])"
.br
.RI "进入shell循环 "
.in -1c
.SH "函数说明"
.PP 
.SS "int SHELL::shell_loop (\fBConsole\fP * model, \fBDisplay\fP * view, \fBExecutor\fP * controller, char * env[])"

.PP
进入shell循环 
.PP
在文件 \fBmyshell\&.cpp\fP 第 \fB71\fP 行定义\&.
.SS "int SHELL::shell_setup (int argc, char * argv[], char * env[])"

.PP
启动shell 
.PP
在文件 \fBmyshell\&.cpp\fP 第 \fB35\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 My Shell 的 源代码自动生成\&.
